export const countryToName: { [key: string]: string } = {
  unknown: "Unclassified",
  gh: "Ghana",
  ga: "Gabon",
  gy: "Guyana",
  gm: "Gambia",
  gg: "Guernsey",
  gp: "Guadeloupe",
  gt: "Guatemala",
  gu: "Guam",
  va: "Vatican City",
  gd: "Grenada",
  gr: "Greece",
  gl: "Greenland",
  gn: "Guinea",
  gw: "Guinea-Bissau",
  na: "Namibia",
  nr: "Nauru",
  ng: "Nigeria",
  ss: "South Sudan",
  za: "South Africa",
  nl: "Netherlands",
  an: "Netherlands Antilles",
  np: "Nepal",
  no: "Norway",
  nc: "New Caledonia",
  nz: "New Zealand",
  nu: "Niue",
  ne: "Niger",
  ni: "Nicaragua",
  tw: "Taiwan",
  kr: "South Korea",
  dk: "Denmark",
  do: "Dominican Republic",
  dm: "Dominica",
  de: "Germany",
  tl: "East Timor",
  la: "Laos",
  lr: "Liberia",
  lv: "Latvia",
  ru: "Russia",
  lb: "Lebanon",
  ls: "Lesotho",
  re: "Réunion",
  ro: "Romania",
  lu: "Luxembourg",
  rw: "Rwanda",
  ly: "Libya",
  lt: "Lithuania",
  li: "Liechtenstein",
  mg: "Madagascar",
  mq: "Martinique",
  mh: "Marshall Islands",
  yt: "Mayotte",
  fm: "Micronesia",
  mo: "Macau",
  mw: "Malawi",
  my: "Malaysia",
  ml: "Mali",
  im: "Isle of Man",
  mx: "Mexico",
  mc: "Monaco",
  ma: "Morocco",
  mu: "Mauritius",
  mr: "Mauritania",
  mz: "Mozambique",
  me: "Montenegro",
  ms: "Montserrat",
  md: "Moldova",
  mv: "Maldives",
  mt: "Malta",
  mn: "Mongolia",
  mm: "Myanmar",
  us: "United States",
  vu: "Vanuatu",
  bh: "Bahrain",
  bb: "Barbados",
  bs: "Bahamas",
  bd: "Bangladesh",
  bm: "Bermuda",
  bj: "Benin",
  ve: "Venezuela",
  vn: "Vietnam",
  be: "Belgium",
  by: "Belarus",
  bz: "Belize",
  ba: "Bosnia and Herzegovina",
  bw: "Botswana",
  bo: "Bolivia",
  bi: "Burundi",
  bf: "Burkina Faso",
  bt: "Bhutan",
  mp: "Northern Mariana Islands",
  mk: "North Macedonia",
  bg: "Bulgaria",
  br: "Brazil",
  bn: "Brunei",
  ws: "Samoa",
  sa: "Saudi Arabia",
  cy: "Cyprus",
  eh: "Sahrawi Arab Democratic Republic (Western Sahara)",
  sm: "San Marino",
  st: "São Tomé and Príncipe",
  pm: "Saint Pierre and Miquelon",
  sn: "Senegal",
  rs: "Serbia",
  sc: "Seychelles",
  sh: "Saint Helena",
  lc: "Saint Lucia",
  vc: "Saint Vincent and the Grenadines",
  kn: "Saint Kitts and Nevis",
  so: "Somalia",
  sb: "Solomon Islands",
  sd: "Sudan",
  sr: "Suriname",
  lk: "Sri Lanka",
  se: "Sweden",
  ch: "Switzerland",
  es: "Spain",
  sk: "Slovakia",
  si: "Slovenia",
  sy: "Syria",
  sl: "Sierra Leone",
  sg: "Singapore",
  ae: "United Arab Emirates",
  aw: "Aruba",
  am: "Armenia",
  ar: "Argentina",
  is: "Iceland",
  ht: "Haiti",
  ie: "Ireland",
  az: "Azerbaijan",
  af: "Afghanistan",
  ad: "Andorra",
  al: "Albania",
  dz: "Algeria",
  ao: "Angola",
  ag: "Antigua and Barbuda",
  ai: "Anguilla",
  er: "Eritrea",
  sz: "Eswatini",
  ee: "Estonia",
  ec: "Ecuador",
  et: "Ethiopia",
  sv: "El Salvador",
  uk: "United Kingdom",
  aq: "British Antarctic Territory",
  vg: "British Virgin Islands",
  io: "British Indian Ocean Territory",
  ye: "Yemen",
  om: "Oman",
  at: "Austria",
  hn: "Honduras",
  wf: "Wallis and Futuna",
  jo: "Jordan",
  ug: "Uganda",
  uy: "Uruguay",
  uz: "Uzbekistan",
  ua: "Ukraine",
  eu: "European Union",
  iq: "Iraq",
  ir: "Iran",
  il: "Israel",
  eg: "Egypt",
  it: "Italy",
  in: "India",
  id: "Indonesia",
  jp: "Japan",
  jm: "Jamaica",
  zm: "Zambia",
  je: "Jersey",
  gq: "Equatorial Guinea",
  ge: "Georgia",
  cn: "China",
  cf: "Central African Republic",
  dj: "Djibouti",
  gi: "Gibraltar",
  zw: "Zimbabwe",
  td: "Chad",
  cz: "Czech Republic",
  cl: "Chile",
  cm: "Cameroon",
  cv: "Cape Verde",
  kz: "Kazakhstan",
  qa: "Qatar",
  kh: "Cambodia",
  ca: "Canada",
  ke: "Kenya",
  ky: "Cayman Islands",
  km: "Comoros",
  xk: "Kosovo",
  cr: "Costa Rica",
  ci: "Ivory Coast",
  co: "Colombia",
  cg: "Congo",
  cd: "Democratic Republic of the Congo",
  cu: "Cuba",
  kw: "Kuwait",
  ck: "Cook Islands",
  hr: "Croatia",
  kg: "Kyrgyzstan",
  ki: "Kiribati",
  tj: "Tajikistan",
  tz: "Tanzania",
  th: "Thailand",
  tc: "Turks and Caicos Islands",
  tg: "Togo",
  to: "Tonga",
  tm: "Turkmenistan",
  tv: "Tuvalu",
  tn: "Tunisia",
  tr: "Türkiye",
  tt: "Trinidad and Tobago",
  pa: "Panama",
  py: "Paraguay",
  pk: "Pakistan",
  pg: "Papua New Guinea",
  pw: "Palau",
  ps: "Palestine",
  pe: "Peru",
  pt: "Portugal",
  pl: "Poland",
  pr: "Puerto Rico",
  fr: "France",
  gf: "French Guiana",
  pf: "French Polynesia",
  fj: "Fiji",
  fi: "Finland",
  ph: "Philippines",
  pn: "Pitcairn Islands",
  hu: "Hungary",
  au: "Australia",
  hk: "Hong Kong",
};
